name: continuous-integration
on: [push]

jobs:

  maven:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout SCM
        uses: actions/checkout@v1

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Build with Maven
        run: mvn --settings settings.xml -B clean install

      - name: Sonar with Maven
        run: mvn --settings settings.xml -B sonar:sonar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN}}

  docker:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout SCM
        uses: actions/checkout@v1

      - name: docker build latest
        if: success()
        run: docker build -t nifi:latest .

      - name: docker login
        run: echo "$GITHUB_TOKEN" | docker login --username "$DOCKER_LOGIN" --password-stdin "$DOCKER_REGISTRY"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: docker push latest
        run: |
          docker tag nifi:latest "$DOCKER_IMAGE":latest
          docker push "$DOCKER_IMAGE":latest
